cmake_minimum_required(VERSION 3.15)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_HOST_SYSTEM_NAME "Windows")
set(LLVM_HOST_TRIPLE aarch64-windows-gnu)
set(LLVM_DEFAULT_TARGET_TRIPLE ${LLVM_HOST_TRIPLE})
set(CMAKE_C_COMPILER_WORKS On)

execute_process(
  COMMAND which llvm-tblgen
  OUTPUT_VARIABLE LLVM_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(LLVM_TABLEGEN ${LLVM_TABLEGEN_PATH})
get_filename_component(LLVM_TOOLCHAIN_BIN ${LLVM_TABLEGEN_PATH} DIRECTORY)

execute_process(
  COMMAND which clang-tblgen
  OUTPUT_VARIABLE CLANG_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_TABLEGEN ${CLANG_TABLEGEN_PATH})
set(CMAKE_CXX_COMPILER_WORKS On)

set(TOOLCHAIN_COMMON_FLAGS "--stdlib=libc++ -Wno-array-bounds -Wno-cast-function-type -Wno-uninitialized -fuse-ld=lld -Wno-misleading-indentation -Wno-global-constructors --rtlib=compiler-rt")
set(CMAKE_C_FLAGS ${TOOLCHAIN_COMMON_FLAGS})
set(CMAKE_CXX_FLAGS ${TOOLCHAIN_COMMON_FLAGS})

set(CMAKE_C_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang)
set(CMAKE_C_COMPILER_TARGET aarch64-windows-gnu)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER_TARGET aarch64-windows-gnu)
set(CMAKE_CXX_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang++)
set(CMAKE_CXX_COMPILER_TARGET aarch64-windows-gnu)
set(CMAKE_AR ${LLVM_TOOLCHAIN_BIN}/llvm-ar)
set(CMAKE_RANLIB ${LLVM_TOOLCHAIN_BIN}/llvm-ranlib)
set(CMAKE_LINKER ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_C_LINK_EXECUTABLE ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_CXX_LINK_EXECUTABLE ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_ASM_LINK_EXECUTABLE ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_EXE_LINKER ${LLVM_TOOLCHAIN_BIN}/lld)

unset(linux)
unset(unix)
unset(Linux)
unset(Unix)
set(MINGW 1)
set(WIN32 1)


set(HAVE_CXX_FLAG_WTHREAD_SAFETY Off)
set(HAVE_STEADY_CLOCK Off)

set(BENCHMARK_ENABLE_TESTING Off)

set(LLVM_OPTIMIZED_TABLEGEN On)
set(LLVM_INCLUDE_BENCHMARKS Off)
set(LLVM_ENABLE_PIC Off)
set(LLVM_ENABLE_ASSERTIONS Off)
set(LLVM_ENABLE_UNWIND_TABLES Off)
set(LLVM_INCLUDE_EXAMPLES Off)
set(LLVM_ENABLE_BACKTRACES Off)
set(LLVM_INCLUDE_TESTS Off)

set(BUILD_SHARED_LIBS On)
set(HAS_WERROR_GLOBAL_CTORS Off)


# libcxx
set(LLVM_ENABLE_RUNTIMES "libcxx;libcxxabi")
set(LIBCXX_CXX_ABI "libcxxabi")
set(LIBCXX_INCLUDE_TESTS Off)
set(LIBCXX_INCLUDE_BENCHMARKS Off)
set(LLVM_RUNTIME_TARGETS ${LLVM_HOST_TRIPLE})

set(LIBCXXABI_ENABLE_THREADS Off)
set(LIBCXXABI_HAS_PTHREAD_API Off)
set(LIBCXXABI_HAS_WIN32_THREAD_API Off)
set(LIBCXXABI_HAS_EXTERNAL_THREAD_API Off)
set(LIBCXXABI_HAS_EXTERNAL_THREAD_API off)
set(LIBCXXABI_USE_LLVM_UNWINDER On)
set(LIBCXXABI_USE_COMPILER_RT On)
set(LIBCXX_USE_COMPILER_RT On)
set(LIBCXX_USE_LLVM_UNWINDER On)
set(LIBCXXABI_SILENT_TERMINATE ON)
set(LIBCXXABI_NON_DEMANGLING_TERMINATE ON)

set(LIBUNWIND_USE_COMPILER_RT On)
set(LIBUNWIND_ENABLE_THREADS Off)