if [ -z ${ARCH+x} ]; then
ARCH=aarch64
fi
TARGETTRIPLE_CPU=${ARCH}
if [[ ${TARGETTRIPLE_CPU} == "aarch64" ]]; then
TARGETTRIPLE_CPU_ALIAS=aarch64
else
TARGETTRIPLE_CPU_ALIAS=${TARGETTRIPLE_CPU}
fi
if [ -z ${ANDROIDAPIVERSION+x} ]; then
ANDROIDAPIVERSION=30
fi
TARGETTRIPLENOVERSION=${TARGETTRIPLE_CPU}-linux-android
TARGETTRIPLE=${TARGETTRIPLENOVERSION}${ANDROIDAPIVERSION}

if [ -z ${SYSTEMNAME+x} ]; then
SYSTEMNAME=Android
fi

if [ -z ${HOST+x} ]; then
HOST=$TARGETTRIPLE
fi

HOST=$HOST SYSTEMNAME=$SYSTEMNAME ./wavm.sh "$@"
exit $?
