if [ -z ${ARCH+x} ]; then
ARCH=aarch64
fi
TARGETTRIPLE_CPU=${ARCH}
if [[ ${TARGETTRIPLE_CPU} == "aarch64" ]]; then
TARGETTRIPLE_CPU_ALIAS=aarch64
else
TARGETTRIPLE_CPU_ALIAS=${TARGETTRIPLE_CPU}
fi
if [ -z ${APPLEDARWINVERSION+x} ]; then
APPLEDARWINVERSION=24
fi
TARGETTRIPLENOVERSION=${TARGETTRIPLE_CPU}-apple-darwin
TARGETTRIPLE=${TARGETTRIPLENOVERSION}${APPLEDARWINVERSION}

if [ -z ${SYSTEMNAME+x} ]; then
SYSTEMNAME=Darwin
fi

if [ -z ${HOST+x} ]; then
HOST=$TARGETTRIPLE
fi

HOST=$HOST SYSTEMNAME=$SYSTEMNAME ./wavm-aarch64-apple-darwin24.sh "$@"
exit $?
