if [ -z ${ARCH+x} ]; then
ARCH=aarch64
fi
TARGETTRIPLE_CPU=${ARCH}
if [[ ${TARGETTRIPLE_CPU} == "aarch64" ]]; then
TARGETTRIPLE_CPU_ALIAS=aarch64
else
TARGETTRIPLE_CPU_ALIAS=${TARGETTRIPLE_CPU}
fi
if [ -z ${ANDROIDAPIVERSION+x} ]; then
ANDROIDAPIVERSION=30
fi
TARGETTRIPLENOVERSION=${TARGETTRIPLE_CPU}-linux-android
TARGETTRIPLE=${TARGETTRIPLENOVERSION}${ANDROIDAPIVERSION}

HOST=$TARGETTRIPLE SYSTEMNAME=Android ./wavm.sh
exit $?
