cmake_minimum_required(VERSION 3.15)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_HOST_SYSTEM_NAME "Windows")
set(LLVM_HOST_TRIPLE x86_64-windows-msvc)
set(LLVM_DEFAULT_TARGET_TRIPLE x86_64-windows-gnu)
set(LLVM_ENABLE_LLD On)
set(LLVM_ENABLE_LTO thin)

set(LLVM_TABLEGEN llvm-tblgen)
set(LLVM_PROFGEN llvm-profgen)
set(LLDB_TBLGEN lldb-tblgen)
set(CLANG_TABLEGEN clang-tblgen)
set(CLANG_PSEUDO_GEN clang-pseudo-gen)
set(CLANG_AST_DUMP clang-ast-dump)

set(TOOLCHAIN_COMMON_FLAGS "-Wno-array-bounds -Wno-cast-function-type -Wno-uninitialized -fuse-ld=lld -Wno-misleading-indentation -Wno-global-constructors -D_HAS_EXCEPTIONS=0 -D_HAS_RTTI=0 -D_DLL=1 -fno-exceptions -fno-rtti")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${TOOLCHAIN_COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TOOLCHAIN_COMMON_FLAGS}")

include_directories(${CMAKE_SYSROOT}/include/um)
include_directories(${CMAKE_SYSROOT}/include/shared)
include_directories(${CMAKE_SYSROOT}/include/ucrt)
include_directories(${CMAKE_SYSROOT}/include/stl)
include_directories(${CMAKE_SYSROOT}/include/winrt)
include_directories(${CMAKE_SYSROOT}/include/cppwinrt)
include_directories(${CMAKE_SYSROOT}/include)
link_directories(${CMAKE_SYSROOT}/lib)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${LLVM_HOST_TRIPLE})
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER_TARGET ${LLVM_HOST_TRIPLE})
set(CMAKE_ASM_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${LLVM_HOST_TRIPLE})
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_LINKER lld)
set(CMAKE_C_LINK_EXECUTABLE lld)
set(CMAKE_CXX_LINK_EXECUTABLE lld)
set(CMAKE_ASM_LINK_EXECUTABLE lld)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ZLIB_LIBRARY ${CMAKE_SYSROOT}/lib/libzlibstatic.lib)
set(ZLIB_INCLUDE_DIR ${CMAKE_SYSROOT}/include)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_EXE_LINKER lld)

unset(linux)
unset(unix)
unset(Linux)
unset(Unix)
set(MSVC 1)
set(WIN32 1)

set(LLVM_ENABLE_PROJECTS "clang;lld;clang-tools-extra")

set(HAVE_CXX_FLAG_WTHREAD_SAFETY Off)
set(HAVE_STEADY_CLOCK Off)

set(BENCHMARK_ENABLE_TESTING Off)

set(LLVM_OPTIMIZED_TABLEGEN On)
set(LLVM_INCLUDE_BENCHMARKS Off)
set(LLVM_ENABLE_PIC Off)
set(LLVM_ENABLE_ASSERTIONS Off)
set(LLVM_ENABLE_UNWIND_TABLES Off)
set(LLVM_INCLUDE_EXAMPLES Off)
set(LLVM_ENABLE_BACKTRACES Off)
set(LLVM_INCLUDE_TESTS Off)

set(HAS_WERROR_GLOBAL_CTORS Off)

link_libraries(-lmsvcrt)
