cmake_minimum_required(VERSION 3.15)

set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(TOOLCHAIN_TRIPLE x86_64-ubuntu-linux-gnu)
set(LLVM_HOST_TRIPLE x86_64-linux-gnu)
set(LLVM_DEFAULT_TARGET_TRIPLE x86_64-linux-gnu)
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_HOST_SYSTEM_NAME ${CMAKE_SYSTEM_NAME})

execute_process(
  COMMAND which ${TOOLCHAIN_TRIPLE}-gcc
  OUTPUT_VARIABLE BINUTILS_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

get_filename_component(TOOLCHAIN_BIN ${BINUTILS_PATH} DIRECTORY)


set(CMAKE_SYSROOT ${TOOLCHAIN_BIN}/..)

execute_process(
  COMMAND which llvm-tblgen
  OUTPUT_VARIABLE LLVM_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(LLVM_TABLEGEN ${LLVM_TABLEGEN_PATH})
get_filename_component(LLVM_TOOLCHAIN_BIN ${LLVM_TABLEGEN_PATH} DIRECTORY)

execute_process(
  COMMAND which clang-tblgen
  OUTPUT_VARIABLE CLANG_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_TABLEGEN ${CLANG_TABLEGEN_PATH})

execute_process(
  COMMAND which clang-pseudo-gen
  OUTPUT_VARIABLE CLANG_PSEUDO_GEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_PSEUDO_GEN ${CLANG_PSEUDO_GEN_PATH})

execute_process(
  COMMAND which llvm-profgen
  OUTPUT_VARIABLE LLVM_PROFGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(LLVM_PROFGEN ${LLVM_PROFGEN_PATH})

execute_process(
  COMMAND which lldb-tblgen
  OUTPUT_VARIABLE LLDB_TBLGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(LLDB_TBLGEN ${LLDB_TBLGEN_PATH})

execute_process(
  COMMAND which clang-ast-dump
  OUTPUT_VARIABLE CLANG_AST_DUMP_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_AST_DUMP ${CLANG_AST_DUMP_PATH})

execute_process(
  COMMAND which clang-tidy-confusable-chars-gen
  OUTPUT_VARIABLE CLANG_TIDY_CONFUSABLE_CHARS_GEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_TIDY_CONFUSABLE_CHARS_GEN ${CLANG_TIDY_CONFUSABLE_CHARS_GEN_PATH})

set(LLVM_OPTIMIZED_TABLEGEN On)
set(BUILD_SHARED_LIBS On)

set(LLVM_ENABLE_PROJECTS "clang;lld;clang-tools-extra")
# runtimes
set(LLVM_ENABLE_RUNTIMES "libcxxabi;libcxx;compiler-rt;libunwind")
set(LIBCXXABI_SILENT_TERMINATE On)
unset(MINGW)
unset(WIN32)
unset(linux)
unset(unix)
unset(LINUX)
unset(UNIX)

set(linux 1)
set(LINUX 1)
set(unix 1)
set(UNIX 1)
set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_CXX_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_AR ${LLVM_TOOLCHAIN_BIN}/llvm-ar)
set(CMAKE_RANLIB ${LLVM_TOOLCHAIN_BIN}/llvm-ranlib)
set(CMAKE_CXXFILT ${LLVM_TOOLCHAIN_BIN}/llvm-cxxfilt)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ZLIB_LIBRARY ${CMAKE_SYSROOT}/${TOOLCHAIN_TRIPLE}/lib64/libzlibstatic.a)
set(ZLIB_INCLUDE_DIR ${CMAKE_SYSROOT}/${TOOLCHAIN_TRIPLE}/include)
set(LLVM_ENABLE_PIC On)
set(LLVM_ENABLE_LLD On)
set(LLVM_ENABLE_LTO thin)
set(LIBCXXABI_SILENT_TERMINATE On)