cmake_minimum_required(VERSION 3.15)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_NAME "wasi")
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_HOST_SYSTEM_NAME "wasi")
set(TOOLCHAIN_TRIPLE wasm32-wasi)
set(LLVM_HOST_TRIPLE wasm32-wasi)
set(LLVM_DEFAULT_TARGET_TRIPLE ${LLVM_HOST_TRIPLE})
set(LLVM_ENABLE_LLD On)

execute_process(
  COMMAND which clang
  OUTPUT_VARIABLE BINUTILS_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

get_filename_component(TOOLCHAIN_BIN ${BINUTILS_PATH} DIRECTORY)

execute_process(
  COMMAND which llvm-tblgen
  OUTPUT_VARIABLE LLVM_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(LLVM_TABLEGEN ${LLVM_TABLEGEN_PATH})
get_filename_component(LLVM_TOOLCHAIN_BIN ${LLVM_TABLEGEN_PATH} DIRECTORY)

execute_process(
  COMMAND which clang-tblgen
  OUTPUT_VARIABLE CLANG_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_TABLEGEN ${CLANG_TABLEGEN_PATH})

set(TOOLCHAIN_COMMON_FLAGS "-Wno-array-bounds -Wno-cast-function-type -Wno-uninitialized -fuse-ld=lld -Wno-misleading-indentation -Wno-global-constructors -Wno-unused-command-line-argument")
set(CMAKE_C_FLAGS ${TOOLCHAIN_COMMON_FLAGS})
set(CMAKE_CXX_FLAGS ${TOOLCHAIN_COMMON_FLAGS})

set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)

set(CMAKE_C_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang)
set(CMAKE_C_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_CXX_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_AR ${LLVM_TOOLCHAIN_BIN}/llvm-ar)
set(CMAKE_RANLIB ${LLVM_TOOLCHAIN_BIN}/llvm-ranlib)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

unset(linux)
unset(Linux)
unset(unix)
unset(UNIX)

set(HAVE_CXX_FLAG_WTHREAD_SAFETY Off)
set(HAVE_STEADY_CLOCK Off)

set(BENCHMARK_ENABLE_TESTING Off)

set(LLVM_OPTIMIZED_TABLEGEN On)
set(LLVM_INCLUDE_BENCHMARKS Off)
set(LLVM_ENABLE_PIC Off)
set(LLVM_ENABLE_ASSERTIONS Off)
set(LLVM_ENABLE_UNWIND_TABLES Off)
set(LLVM_INCLUDE_EXAMPLES Off)
set(LLVM_ENABLE_BACKTRACES Off)
set(LLVM_INCLUDE_TESTS Off)
set(LIBCXXABI_SILENT_TERMINATE On)
set(BUILD_SHARED_LIBS On)
set(HAS_WERROR_GLOBAL_CTORS Off)
set(LIBCXX_CXX_ABI libcxxabi)
set(LIBCXX_HAS_WIN32_THREAD_API Off)
set(LIBCXX_HAS_MUSL_LIBC On)
set(LIBCXX_HAS_PTHREAD_API Off)
set(LIBCXX_BUILD_EXTERNAL_THREAD_LIBRARY Off)
set(LIBCXX_ENABLE_THREADS Off)
set(LIBCXXABI_ENABLE_EXCEPTIONS Off)
set(LIBCXXABI_ENABLE_SHARED Off)
set(LIBCXX_BUILD_EXTERNAL_THREAD_LIBRARY Off)
set(LIBCXX_ENABLE_EXCEPTIONS Off)
set(LIBCXX_ENABLE_RTTI Off)
set(LIBCXXABI_ENABLE_RTTI Off)
set(LIBCXX_INCLUDE_BENCHMARKS Off)
set(LIBCXX_ENABLE_FILESYSTEM Off)
set(LIBCXXABI_ENABLE_THREADS Off)
set(LIBCXX_ENABLE_SHARED Off)

# libcxx
set(LLVM_ENABLE_RUNTIMES "libcxx;libcxxabi")
set(COMPILER_RT_BUILD_LIBFUZZER Off)
set(LLVM_RUNTIME_TARGETS ${LLVM_HOST_TRIPLE})
set(WASI 1)