cmake_minimum_required(VERSION 3.15)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_NAME "wasi")
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_HOST_SYSTEM_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR})
set(CMAKE_HOST_SYSTEM_NAME "wasi")
set(TOOLCHAIN_TRIPLE wasm32-wasi)
set(LLVM_HOST_TRIPLE wasm32-wasi)
set(LLVM_DEFAULT_TARGET_TRIPLE ${LLVM_HOST_TRIPLE})
set(LLVM_ENABLE_LLD On)

execute_process(
  COMMAND which clang
  OUTPUT_VARIABLE BINUTILS_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

get_filename_component(TOOLCHAIN_BIN ${BINUTILS_PATH} DIRECTORY)

execute_process(
  COMMAND which llvm-tblgen
  OUTPUT_VARIABLE LLVM_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(LLVM_TABLEGEN ${LLVM_TABLEGEN_PATH})
get_filename_component(LLVM_TOOLCHAIN_BIN ${LLVM_TABLEGEN_PATH} DIRECTORY)

execute_process(
  COMMAND which clang-tblgen
  OUTPUT_VARIABLE CLANG_TABLEGEN_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CLANG_TABLEGEN ${CLANG_TABLEGEN_PATH})

set(TOOLCHAIN_COMMON_FLAGS "-Wno-array-bounds -Wno-cast-function-type -Wno-uninitialized -fuse-ld=lld -Wno-misleading-indentation -Wno-global-constructors -flto=thin -Wno-unused-command-line-argument")
set(CMAKE_C_FLAGS ${TOOLCHAIN_COMMON_FLAGS})
set(CMAKE_CXX_FLAGS ${TOOLCHAIN_COMMON_FLAGS})

set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)

set(CMAKE_C_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang)
set(CMAKE_C_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_CXX_COMPILER ${LLVM_TOOLCHAIN_BIN}/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${TOOLCHAIN_TRIPLE})
set(CMAKE_AR ${LLVM_TOOLCHAIN_BIN}/llvm-ar)
set(CMAKE_RANLIB ${LLVM_TOOLCHAIN_BIN}/llvm-ranlib)
set(CMAKE_LINKER ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_C_LINK_EXECUTABLE ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_CXX_LINK_EXECUTABLE ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_ASM_LINK_EXECUTABLE ${LLVM_TOOLCHAIN_BIN}/lld)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_EXE_LINKER ${LLVM_TOOLCHAIN_BIN}/lld)
set(COMPILER_RT_DEFAULT_TARGET_ARCH ${CMAKE_SYSTEM_PROCESSOR})
set(COMPILER_RT_DEFAULT_TARGET_TRIPLE ${LLVM_HOST_TRIPLE})


unset(linux)
unset(Linux)
set(unix 1)


set(HAVE_CXX_FLAG_WTHREAD_SAFETY Off)
set(HAVE_STEADY_CLOCK Off)

set(BENCHMARK_ENABLE_TESTING Off)

set(LLVM_OPTIMIZED_TABLEGEN On)
set(LLVM_INCLUDE_BENCHMARKS Off)
set(LLVM_ENABLE_PIC Off)
set(LLVM_ENABLE_ASSERTIONS Off)
set(LLVM_ENABLE_UNWIND_TABLES Off)
set(LLVM_INCLUDE_EXAMPLES Off)
set(LLVM_ENABLE_BACKTRACES Off)
set(LLVM_INCLUDE_TESTS Off)
set(COMPILER_RT_OS_DIR wasi)
set(WASI 1)
set(COMPILER_RT_BAREMETAL_BUILD On)
set(BUILD_SHARED_LIBS On)
set(HAS_WERROR_GLOBAL_CTORS Off)
set(COMPILER_RT_HAS_FPIC_FLAG OFF)

# libcxx
set(LLVM_ENABLE_RUNTIMES "compiler-rt")
set(COMPILER_RT_BUILD_LIBFUZZER Off)
set(LLVM_RUNTIME_TARGETS ${LLVM_HOST_TRIPLE})
